(defpackage :senn.win.im.can-process
  (:use :cl)
  (:export :execute))
(in-package :senn.win.im.can-process)

(defgeneric execute (state key mode))

(defmethod execute ((s senn.im.inputting:state)
                    (key senn.win.keys:key)
                    (mode (eql :direct)))
  t)

(defmethod execute ((s senn.im.converting:state)
                    (key senn.win.keys:key)
                    (mode (eql :direct)))
  t)

(defmethod execute ((s t)
                    (key senn.win.keys:key)
                    (mode (eql :direct)))
  nil)

(defmethod execute ((s senn.im.converting:state)
                    (key senn.win.keys:key)
                    (mode (eql :hiragana)))
  (cond ((senn.win.keys:enter-p key) t)
        ((or (senn.win.keys:space-p key)
             (senn.win.keys:down-p key))
         t)
        ((senn.win.keys:up-p key) t)
        ((senn.win.keys:left-p key) t)
        ((senn.win.keys:right-p key) t)
        (t nil)))

(defmethod execute ((s senn.im.inputting:state)
                    (key senn.win.keys:key)
                    (mode (eql :hiragana)))
  (cond ((senn.win.keys:oem-minus-p key) t)
        ((senn.win.keys:oem-7-p key) t)
        ((senn.win.keys:oem-5-p key) t)
        ((senn.win.keys:oem-3-p key) t)
        ((senn.win.keys:oem-4-p key) t)
        ((senn.win.keys:oem-plus-p key) t)
        ((senn.win.keys:oem-1-p key) t)
        ((senn.win.keys:oem-6-p key) t)
        ((senn.win.keys:oem-comma-p key) t)
        ((senn.win.keys:oem-period-p key) t)
        ((senn.win.keys:oem-2-p key) t)
        ((senn.win.keys:oem-102-p key) t)
        ((senn.win.keys:number-p key) t)
        ((senn.win.keys:alphabet-p key) t)
        ((senn.win.keys:backspace-p key)
         ;; IMEが文字を削除していない -> OSに文字を削除してもらう
         (not (senn.im.inputting:state-buffer-empty-p s)))
        ((senn.win.keys:space-p key)
         (not (senn.im.inputting:state-buffer-empty-p s)))
        ((senn.win.keys:enter-p key) t)
        (t nil)))
