(defpackage :senn.gui.menu.about
  (:use :cl)
  (:export :show))
(in-package :senn.gui.menu.about)
(named-readtables:in-readtable :qt)

(defclass dialog ()
  ()
  (:metaclass qt:qt-class)
  (:qt-superclass "QWidget"))

(defmethod initialize-instance :after ((dialog dialog) &key)
  (qt:new dialog)
  (#_setFixedSize dialog (floor (* 200 1.1618 2)) 200)
  (#_setWindowTitle dialog "About Senn")
  (let ((name (#_new QLabel "Senn" dialog)))
    (let ((font (#_font name)))
      (#_setPointSize font 36)
      (#_setBold font t)
      (#_setFont name font))
    (#_move name 20 20))
  (#_move (#_new QLabel "Senn is an input method editor for the Japanese language." dialog) 20 100))

(defun show ()
  (qt:with-main-window (dialog (make-instance 'dialog))))
